import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, ChevronRight } from "lucide-react";
import { notFound } from "next/navigation";
import { ProductCard } from "@/components/product-card";
import { ProductGallery } from "@/components/product-gallery";
import { formatPrice, getProductBySlug, getProductsByCategory, getProductsBySubcategory, products, toCatalogProduct } from "@/data/products";
export function generateStaticParams() { return products.map((product) => ({ slug: product.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const product = getProductBySlug((await params).slug); return product ? { title: product.name, description: product.shortDescription, alternates: { canonical: `/products/${product.slug}` }, openGraph: { images: [{ url: product.images[0] }] } } : {}; }
export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) { const product = getProductBySlug((await params).slug); if (!product) notFound(); const related = getProductsBySubcategory(product.subcategory).filter((item) => item.id !== product.id).slice(0,3); const complements = getProductsByCategory(product.category).filter((item) => item.id !== product.id && item.subcategory !== product.subcategory).slice(0,3); return <><nav className="breadcrumb shell"><Link href="/shop">Shop</Link><ChevronRight size={12}/><Link href={`/collections/${product.category.toLowerCase()}`}>{product.category}</Link><ChevronRight size={12}/><span>{product.name}</span></nav><section className="product-detail shell"><ProductGallery images={product.images} name={product.name}/><aside className="product-info"><p className="eyebrow">{product.category} / {product.subcategory}</p><h1>{product.name}</h1><div className="detail-price">{formatPrice(product.price)}</div><p className="product-lede">{product.shortDescription}</p><p className="product-description">{product.description}</p><dl className="spec-list"><div><dt>Finish</dt><dd>{product.colors.join(" / ")}</dd></div><div><dt>Materials</dt><dd>{product.materials.join(" / ")}</dd></div><div><dt>Dimensions</dt><dd>{product.dimensions}</dd></div></dl><p className="product-note">Reference price and availability captured on {product.dateCaptured}. Confirm with the studio.</p></aside></section><section className="related"><div className="shell"><div className="section-heading"><div><p className="eyebrow">MORE LIKE THIS</p><h2>Continue the edit.</h2></div><Link className="text-link" href={`/collections/${product.category.toLowerCase()}`}>View {product.category} <ArrowRight size={16}/></Link></div><div className="product-grid">{(related.length ? related : complements).map((item) => <ProductCard product={toCatalogProduct(item)} key={item.id}/>)}</div></div></section></>; }
