import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { ShopCatalog } from "@/components/shop-catalog";
import { categories, getProductsByCategory, toCatalogProduct, type Category } from "@/data/products";
const content: Record<Category, { title: string; description: string; image: string }> = { Living: { title: "Rooms made to linger.", description: "Low seating, sculptural chairs, and mineral tables for the hours that stretch easily.", image: "/editorial/living-hero.webp" }, Dining: { title: "Gather around good design.", description: "Tables and chairs with enough presence for an everyday dinner and a full house.", image: "/editorial/dining-hero.webp" }, Bedroom: { title: "A softer kind of architecture.", description: "Grounded beds and quiet storage for an end-of-day reset.", image: "/editorial/bedroom-hero.webp" }, Outdoor: { title: "Outside, considered.", description: "Weather-ready pieces for terraces, gardens, and late light.", image: "/editorial/outdoor-hero.webp" } };
const getCategory = (slug: string) => categories.find((category) => category.toLowerCase() === slug);
export function generateStaticParams() { return categories.map((category) => ({ category: category.toLowerCase() })); }
export async function generateMetadata({ params }: { params: Promise<{ category: string }> }): Promise<Metadata> { const category = getCategory((await params).category); return category ? { title: `${category} Furniture`, description: content[category].description } : {}; }
export default async function CategoryPage({ params }: { params: Promise<{ category: string }> }) { const category = getCategory((await params).category); if (!category) notFound(); const details = content[category]; const products = getProductsByCategory(category); return <><header className="franze-category-masthead shell"><p className="franze-kicker">ROOM EDIT / {products.length} PIECES</p><div><h1>{category}</h1><p>{details.title}</p></div><div className="franze-category-photo"><Image src={details.image} alt={`${category} collection`} fill priority sizes="(max-width: 780px) 100vw, 32vw" unoptimized /></div><p className="franze-category-description">{details.description}</p></header><ShopCatalog initialProducts={products.map(toCatalogProduct)} initialCategory={category} /></>; }
